version: "3"
services:
  api:
    build: .
    ports:
      - '3002:3002'
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - internalnet

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'todolist'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
