node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
       def app = docker.build("ngocphupham/todolist:${commit_id}", '.').push()
     }
   }
  stage('deploy'){
    steps {
      dir('/home/devops/todo') {
        sh 'git pull'
      }
    }
  }
}
