export default {
  PORT: process.env.API_PORT,
  HOST: process.env.API_HOST,
  API_ACCESS_TOKEN_SECRET: process.env.API_ACCESS_TOKEN_SECRET,
  API_ACCESS_TOKEN_TTL_IN_MINUTES: process.env.API_ACCESS_TOKEN_SECRET,
  API_ACCESS_TOKEN_HEADER: process.env.API_ACCESS_TOKEN_HEADER,
  API_LOGIN_USERNAME_FIELD: process.env.API_LOGIN_USERNAME_FIELD,
  API_LOGIN_PASSWORD_FIELD: process.env.API_LOGIN_PASSWORD_FIELD,
  API_LIMIT_NUMBER: process.env.API_LIMIT_NUMBER,
  API_DURATION_NUMBER: process.env.API_DURATION_NUMBER,
  LOG_ENABLE: process.env.LOG_ENABLE,
};
